# Generated by Django 6.0.7 on 2026-08-01 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'intrant", max_length=150)),
                ('description', models.TextField(blank=True, help_text="Description de l'intrant")),
                ('quantite', models.DecimalField(decimal_places=2, default=0, help_text='Quantité disponible', max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('unite', 'Unité'), ('m2', 'Mètres carrés'), ('m3', 'Mètres cubes')], default='kg', help_text='Unité de mesure', max_length=10)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=2, help_text='Seuil de stock bas', max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Intrant',
                'verbose_name_plural': 'Intrants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], help_text='Type de mouvement', max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité mouvementée', max_digits=10)),
                ('date_mouvement', models.DateField(help_text='Date du mouvement')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire sur le mouvement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('intrant', models.ForeignKey(help_text='Intrant concerné par le mouvement', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.intrant')),
                ('responsable', models.ForeignKey(blank=True, help_text='Utilisateur responsable du mouvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
