# Generated by Django 6.0.7 on 2026-08-01 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
        ('parcelles', '0002_parcelle_irrigation_parcelle_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du client', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email du client', max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone du client', max_length=20)),
                ('adresse', models.TextField(blank=True, help_text='Adresse du client')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description de la vente')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', help_text='Statut de la commande', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Montant total de la vente', max_digits=12)),
                ('date_commande', models.DateField(help_text='Date de la commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('client', models.ForeignKey(blank=True, help_text='Client de la vente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='ventes.client')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable de la vente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_commande', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='VenteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité vendue', max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire', max_digits=12)),
                ('culture', models.ForeignKey(blank=True, help_text='Culture vendue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_articles', to='cultures.culture')),
                ('parcelle', models.ForeignKey(blank=True, help_text='Parcelle associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vente_articles', to='parcelles.parcelle')),
                ('vente', models.ForeignKey(help_text='Vente associée', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Article de vente',
                'verbose_name_plural': 'Articles de vente',
            },
        ),
    ]
