# Generated by Django 6.0.7 on 2026-08-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Code postal', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('commerce', 'Commerce'), ('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', help_text='Type de client', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, help_text='Ville', max_length=100),
        ),
    ]
