# Generated by Django 6.0.7 on 2026-07-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la culture', max_length=150)),
                ('variete', models.CharField(help_text='Variété de la culture', max_length=150)),
                ('date_semis', models.DateField(help_text='Date de semis ou de plantation')),
                ('date_prevision_recolte', models.DateField(help_text='Date prévue de récolte')),
                ('rendement_attendu', models.DecimalField(blank=True, decimal_places=2, help_text='Rendement attendu en kg/m²', max_digits=7, null=True)),
                ('statut', models.CharField(choices=[('en_croissance', 'En croissance'), ('mature', 'Mature'), ('recolte', 'Récolte'), ('terminee', 'Terminée')], default='en_croissance', help_text='Statut actuel de la culture', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur la culture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, help_text="Date de dernière modification de l'enregistrement")),
                ('parcelle', models.ForeignKey(help_text='Parcelle associée à la culture', on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'db_table': 'cultures_culture',
                'ordering': ['-date_semis'],
            },
        ),
    ]
