# Generated by Django 6.0.7 on 2026-08-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
        ('parcelles', '0002_parcelle_irrigation_parcelle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de récolte')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité récoltée', max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'kg'), ('l', 'L'), ('unite', 'Unité'), ('panier', 'Panier')], default='kg', help_text='Unité de mesure', max_length=20)),
                ('qualite', models.CharField(choices=[('excellente', 'Excellente'), ('bonne', 'Bonne'), ('acceptable', 'Acceptable'), ('mauvaise', 'Mauvaise')], default='bonne', help_text='Qualité de la récolte', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('culture', models.ForeignKey(help_text='Culture récoltée', on_delete=django.db.models.deletion.PROTECT, related_name='recoltes', to='cultures.culture')),
                ('parcelle', models.ForeignKey(help_text='Parcelle de la récolte', on_delete=django.db.models.deletion.PROTECT, related_name='recoltes', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-date'],
            },
        ),
    ]
