# Generated by Django 6.0.7 on 2026-08-01 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultures', '0001_initial'),
        ('parcelles', '0002_parcelle_irrigation_parcelle_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'activité", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée')),
                ('type_activite', models.CharField(choices=[('semis', 'Semis / Plantation'), ('entretien', 'Entretien'), ('irrigation', 'Irrigation'), ('recolte', 'Récolte'), ('ventes', 'Ventes'), ('transport', 'Transport'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifie', max_length=20)),
                ('date_debut', models.DateField(help_text="Date de début de l'activité")),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin prévue', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('culture', models.ForeignKey(blank=True, help_text="Culture concernée par l'activité", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='cultures.culture')),
                ('parcelle', models.ForeignKey(blank=True, help_text="Parcelle concernée par l'activité", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='parcelles.parcelle')),
                ('responsable', models.ForeignKey(blank=True, help_text="Responsable de l'activité", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_debut', 'titre'],
            },
        ),
    ]
