# Generated by Django 6.0.7 on 2026-07-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou identifiant de la parcelle', max_length=100)),
                ('code', models.CharField(help_text='Code unique de la parcelle', max_length=50, unique=True)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en m² ou hectares', max_digits=10)),
                ('type_sol', models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('calcaire', 'Calcaire'), ('organique', 'Organique'), ('mixte', 'Mixte')], default='mixte', help_text='Type de sol de la parcelle', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS', max_digits=9, null=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la parcelle')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_preparation', 'En préparation'), ('reposante', 'Reposante'), ('suspendu', 'Suspendu')], default='actif', help_text='Statut actuel de la parcelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la parcelle')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
                ('exploitation', models.ForeignKey(help_text='Exploitation à laquelle appartient cette parcelle', on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='exploitation.exploitation')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'db_table': 'parcelles_parcelle',
                'ordering': ['nom'],
            },
        ),
    ]
