# Generated by Django 6.0.7 on 2026-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='irrigation',
            field=models.BooleanField(default=False, help_text="Indique si la parcelle dispose d'un système d'irrigation"),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo de la parcelle', null=True, upload_to='parcelles/'),
        ),
    ]
