# Generated by Django 6.0.7 on 2026-08-01 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], help_text='Type de transaction', max_length=10)),
                ('titre', models.CharField(help_text='Titre de la transaction', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la transaction', max_digits=12)),
                ('categorie', models.CharField(choices=[('vente', 'Vente'), ('subvention', 'Subvention'), ('achat', 'Achat'), ('salaires', 'Salaires'), ('entretien', 'Entretien'), ('autre', 'Autre')], default='autre', help_text='Catégorie financière', max_length=20)),
                ('date_operation', models.DateField(help_text='Date de la transaction')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('responsable', models.ForeignKey(blank=True, help_text='Utilisateur responsable de la transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_operation', '-date_creation'],
            },
        ),
    ]
